#-------------------------------------------------#
#           GENERAL                               #
#-------------------------------------------------#
version: 2.0.0.{build}

branches:
 only:
  - master

configuration: Release

platform: Any CPU

init:
- ps: $Env:LABEL = $Env:APPVEYOR_BUILD_NUMBER
  
before_build:
- appveyor-retry dotnet restore -v Minimal

build_script:
- dotnet build "src\FlexMapper" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\FlexMapper.UnitTests" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%

test_script:
- dotnet test "src\FlexMapper.UnitTests" -c %CONFIGURATION%

# after_build:
- dotnet pack "src\FlexMapper" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts

artifacts:
- path: artifacts\**\*.*

cache:
- '%USERPROFILE%\.nuget\packages'

deploy:
  provider: NuGet
  api_key:
    secure: 2uMFkotaBEOwDusxxurI3dmBWqkDDQHPRRdpp6ML4r/mPbIPyD3pxgOsinRQ1Kkf
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/
  on:
    appveor_repo_tag: true  # deploy only when creating a tag in GitHub (Release)