#-------------------------------------------------#
#           GENERAL                               #
#-------------------------------------------------#
version: 2.0.0.{build}

branches:
 only:
  - master

configuration:
- Debug
- Release

platform: Any CPU

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
  
before_build:
- appveyor-retry dotnet restore -v Minimal

build_script:
- dotnet build "src\FlexMapper" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\FlexMapper.UnitTests" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%

test_script:
- dotnet test "src\FlexMapper.UnitTests" -c %CONFIGURATION%

# after_build:
# - dotnet pack "src\FlexMapper" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts

artifacts:
- path: artifacts\**\*.*

cache:
- '%USERPROFILE%\.nuget\packages'

